name: Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deploy-backend
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Write env file
        run: printf '%s' "${{ secrets.REWARD_BACKEND_ENV }}" > .env

      - name: Give permission to script
        run: chmod +x ./scripts/deploy-backend.sh

      - name: Run deploy script
        run: ./scripts/deploy-backend.sh
